name: 'helmfile updater'
description: 'lazy guys action'
inputs:
  repository:
    description: 'target repository'
    required: true
  file:
    description: 'target file'
    required: true
  branch:
    description: 'target branch'
    required: true
  key:
    description: 'object key'
    required: true
  value:
    description: 'set value'
    required: true
runs:
  using: 'node20'
  main: 'index.mjs'
