name: 'helmfile updater'
description: 'lazy guys action'
inputs:
  token:
    description: 'github token'
    required: true
    default: ${{ github.token }}
  file:
    description: 'target file'
    required: true
  key:
    description: 'object key'
    required: true
  value:
    description: 'set value'
    required: true
runs:
  using: "composite"
  steps:
    - run: node ${{ github.action_path }}/index.mjs
      shell: bash
    - run: git commit -a
      shell: bash
